### ISSUE TITLE
can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by VYRION-Ai** [WZS666/Yolov5_DeepSort_SpeedEstimate#1]
```
Traceback (most recent call last):
  File "track.py", line 350, in <module>
    detect(args)
  File "track.py", line 262, in detect
    outputs = deepsort.update(xywhs, confss, myclasses, im0)
  File "E:\Python\Car_Project\Yolov5_DeepSort_SpeedEstimate-main\Yolov5_DeepSort_SpeedEstimate-main\deep_sort_pytorch\deep_sort\deep_sort.py", line 51, in update
    outputs.append(np.array([x1, y1, x2, y2, track_id, class_id], dtype=np.int))
  File "C:\Users\Hamaza & Mariam\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\_tensor.py", line 680, in __array__
    return self.numpy().astype(dtype, copy=False)
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

**Comment by VYRION-Ai** [comment]
this Happened only when using Gup

**Comment by WZS666** [comment]
Hi @totoadel thx for the commented.
Yes, Because it gonna use numpy dtype in Tensor. It only work on CPU. So the way to fix it. You need to edit the _tensor.py.
The path you're using I think it might be :
C:\Users\Hamaza & Mariam\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\_tensor.py

Find the code below:
```
def __array__(self, dtype=None):
        if has_torch_function_unary(self):
            return handle_torch_function(Tensor.__array__, (self,), self, dtype=dtype)
        if dtype is None:
            return self.numpy()
        else:
            return self.numpy().astype(dtype, copy=False)
```

And add the `cpu().detach()` down below:
```
def __array__(self, dtype=None):
        if has_torch_function_unary(self):
            return handle_torch_function(Tensor.__array__, (self,), self, dtype=dtype)
        if dtype is None:
            return self.numpy()
        else:
            return self.cpu().detach().numpy().astype(dtype, copy=False)
```

Hope it can help you to fix the problem !

**Comment by VYRION-Ai** [comment]
@WZS666 thank you very much, it works,
But car speed it not accurate how to fix that < it change allot and show wrong speed

**Comment by WZS666** [comment]
@totoadel you're welcome.
For now in our project we had to measure the real world's features to calculate it in 3d position.
So for the speed estimate. we're still finding the way to make it more robust and match with the real world.
If you had any suggest or comment it'll be our pleasure to have it. Thanks!

**Comment by VYRION-Ai** [comment]
@WZS666 thank you very much for your great work, i hope you will hit your goal soon, i am sorry if my comments make any bad experience, than you

**Comment by WZS666** [comment]
@totoadel Thank you! every comments are all great communicate. There's no any bad experience. :>
