### ISSUE TITLE
id list is like this  , wrong identity order number[1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 23]

### ISSUE THREAD

**Issue by VYRION-Ai** [WZS666/Yolov5_DeepSort_SpeedEstimate#2]
the code works ,OK, but [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 23]
this is how the identity number is showing up 
after 9 i got 11 and then 23
where is 10 and 12.....

**Comment by WZS666** [comment]
@totoadel thx for ur Issues.
I think its detection's problem.
maybe you can try yolov5's weight [yolov5 releases](https://github.com/ultralytics/yolov5/releases)

**Comment by VYRION-Ai** [comment]
I already use it

**Comment by VYRION-Ai** [comment]
> @totoadel thx for ur Issues. I think its detection's problem. maybe you can try yolov5's weight [yolov5 releases](https://github.com/ultralytics/yolov5/releases)

And if the detection is wrong, we will find the missing numbers

**Comment by WZS666** [comment]
But for ur situation those numbers just disappear?

**Comment by VYRION-Ai** [comment]
> But for ur situation those numbers just disappear?
What Do you mean by just disappear?

Where is the error that make it disappears?
