### ISSUE TITLE
this is not an issue, just i have a questions

### ISSUE THREAD

**Issue by VYRION-Ai** [WZS666/Yolov5_DeepSort_SpeedEstimate#3]
thank you a lot for your hard work @WZS666 
but, please i need to know some information,
the first one:-
what do you mean by these , and what values should i use or depends on what 
`    how_many_frame_will_detect = 30
     video_frame_rate = 30`

the second:-
do i have to Chang these values , and where i can calculate them 

` focal length : focal length of the camera (from matlab calibration application)
    # principlepoint : (px, py) (from matlab calibration application)`

the third :
what is the different between those 

`           #velocity_y = alpha * math.sqrt((loc2[0] - loc1[0]) ** 2) / (how_many_frame_will_detect / video_frame_rate) # only see x
            # velocity_y = alpha * math.sqrt((loc2[2] - loc1[2]) ** 2) / (how_many_frame_will_detect / video_frame_rate) # only see z
            #velocity_y = alpha * math.sqrt(sum((loc2 - loc1) ** 2)) / ((how_many_frame_will_detect) / video_frame_rate)`

.

**Comment by WZS666** [comment]
1.It's depends on your video fps. Otherwise the video will speed up very much
2.Yes, it should be change when you testing by your own video, you can calculate by Matlab
3.It's our testing code. you change choose only use x coordinate or z or both sum to do the calculate.

**Comment by VYRION-Ai** [comment]
@WZS666 
i understand the  **video_frame_rate**(fbs), 
but what did you mean by  **how_many_frame_will_detect** ,
did you mean the hole frames in the video or what,

**Comment by WZS666** [comment]
Hello totoadel,
It's mean how much frame I will use for detect.
It's will alteration the velocity part.

**Comment by VYRION-Ai** [comment]
@WZS666 i am sorry, how i decide what value i should use?

**Comment by WZS666** [comment]
For us we adjust it by testing. If our test video got lower fps, then we'll lower the value.
But it'll be better same as the frame rate
