### ISSUE TITLE
Another request, how can it be applied to the road to be angled or rounded?

### ISSUE THREAD

**Issue by VYRION-Ai** [WZS666/Yolov5_DeepSort_SpeedEstimate#4]
@WZS666 another request ,The road is perpendicular to the camera or parallel to it, how can it be applied to the road to be  or rounded?
<a href="https://ibb.co/CHn3g3c"><img src="https://i.ibb.co/1m9t1tg/IMG-0168.jpg" alt="IMG-0168" border="0" /></a>

**Comment by WZS666** [comment]
@totoadel sorry for reply late.
For rounded road. I think you should considering of the vehicle motion characteristics or others vehicle dynamics theory to do the calculation.
refer: https://patents.google.com/patent/CN105118316A/en

**Comment by VYRION-Ai** [comment]
@WZS666 thank you very much
your code helped to calculate object distance from the camera .
I appreciate your effort so much
