### ISSUE TITLE
three_dimension参数设置问题

### ISSUE THREAD

**Issue by hzq1112** [WZS666/Yolov5_DeepSort_SpeedEstimate#7]
您好，请问three_dimension函数中参数的设置是依据什么的呢

**Comment by WZS666** [comment]
您好，不好意思晚回覆。
three_dimension，是依據我們在架設攝像頭位置進行測量後進行設置的。

**Comment by hzq1112** [comment]
您好，再次打扰您。
我是不是可以这么理解：   不同的架设角度  这里的参数设置就需要变动

**Comment by WZS666** [comment]
是的，事實上目前還找不到能夠 robust 應對不同位置的 three_dimension 參數，
如果有任何 refer 歡迎提供給我們，非常感謝。
