### ISSUE TITLE
best_yolov5s_aihub_finetune.pt is not available now.

### ISSUE THREAD

**Issue by 2369257907** [WZS666/Yolov5_DeepSort_SpeedEstimate#8]
[best_yolov5s_aihub_finetune.pt](https://drive.google.com/file/d/1s37buFRyMq1cZkigkTt3m8FDgy5RYRwL/view?usp=sharing) is not available now.
plz check the link.

**Comment by WZS666** [comment]
Hello, thank you for let's me know.
I already update the url.
