### ISSUE TITLE
no such a file

### ISSUE THREAD

**Issue by wangyf8848** [WZS666/Yolov5_DeepSort_SpeedEstimate#9]
Excuse me，this is a exception on "No such file or directory: 'deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7'". How can i get such a file?

**Comment by WZS666** [comment]
Greetings, you can download it from here [ckpt.t7](https://drive.google.com/file/d/1L0RlVqyrOLvjuSA4uuvkdL7IEeE7G6rz/view?usp=sharing)
